### ISSUE TITLE
How to verify your trained models on the test data (chromosome 2)?

### ISSUE THREAD

**Issue by turningpoint1988** [seqcode/cross-species-domain-adaptation#4]
I did not find the source code for verifying the trained models on the test data. Could you please offer the source code about it? Many thanks.

**Comment by kellycochran** [comment]
Hello,

To evaluate the models on the test set, you can first generate model predictions for the test set using the notebook 3_manuscript_figure_and_table_notebooks/0_generate_predictions_for_other_notebooks.ipynb. Then, you can load the predictions and the true labels into another notebook to look at performance metrics including the auPRC, such as what is shown in the notebook 3_manuscript_figure_and_table_notebooks/Figures_3_6_9-auPRC_Dot_Plots.ipynb. Hope this helps!

**Comment by turningpoint1988** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您所发的邮件已收到，我会尽快给您回复。

**Comment by turningpoint1988** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您所发的邮件已收到，我会尽快给您回复。
