### ISSUE TITLE
0_generate_predictions_for_other_notebooks.ipynb can not work, since flipGradient module Error.

### ISSUE THREAD

**Issue by XuanrZhang** [seqcode/cross-species-domain-adaptation#5]
Hi kelly,   @kellycochran @shaunmahony 

Can you share flipGradientTF.py file you use in "0_generate_predictions_for_other_notebooks.ipynb" ?
 
Since the flipGradientTF.py I downloaded from [GitHub](https://github.com/michetonu/gradient_reversal_keras_tf) only works with Tensorflow <2.0.0

In the '0_generate_predictions_for_other_notebooks.ipynb' script,

from flipGradientTF import GradientReversal didn't work.

Any suggestion for getting the updated flipGradienTF.py file?

Thanks in advance.

Xuan

**Comment by kellycochran** [comment]
Hi Xuan,

The flipGradientTF.py file that is at https://github.com/seqcode/cross-species-domain-adaptation/blob/main/3_manuscript_figure_and_table_notebooks/flipGradientTF.py should work using Tensorflow 2.1.0. Could you share the error message that results when you try to run the notebook as-is?

**Comment by XuanrZhang** [comment]
Hi Kelly, 
Many thanks, The problem is solved.
Best,
Xuan
