### ISSUE TITLE
Is it possible for you share the bed file with unbound/bound ALU regions?

### ISSUE THREAD

**Issue by sheetalgiri** [seqcode/cross-species-domain-adaptation#7]
Due to some technical issues I was unable to setup peak calling with MultiGPS and unable to generate the positive/negative window files chr3toY_pos_shuf.bed and chr3toY_pos_shuf.bed. I imagine these files are quite big, could the authors please share a bed file with ALU regions that overlaps with bound/unbound regions ?

**Comment by kellycochran** [comment]
Hi Sheetal,

Feel free to use the following links to see the files:

alus.bed, a bed file containing all the hg38 Alu regions: [https://mitra.stanford.edu/kundaje/oak/kcochran/domain_adaptation_nosexchr/data/hg38/alus.bed](https://mitra.stanford.edu/kundaje/oak/kcochran/domain_adaptation_nosexchr/data/hg38/alus.bed) 

chr3toY_neg_shuf.bed, a bed file containing all genomic windows *not bound* by CTCF, for all chromosomes except 1,2,M,X,Y (apologies that the filename is confusing, but chrX/chrY are not used): [https://mitra.stanford.edu/kundaje/oak/kcochran/domain_adaptation_nosexchr/data/hg38/CTCF/chr3toY_neg_shuf.bed](https://mitra.stanford.edu/kundaje/oak/kcochran/domain_adaptation_nosexchr/data/hg38/CTCF/chr3toY_neg_shuf.bed)

chr3toY_pos_shuf.bed, a bed file containing all genomic windows *bound* by CTCF on all chromosomes except 1,2,M,X,Y: [https://mitra.stanford.edu/kundaje/oak/kcochran/domain_adaptation_nosexchr/data/hg38/CTCF/chr3toY_pos_shuf.bed](https://mitra.stanford.edu/kundaje/oak/kcochran/domain_adaptation_nosexchr/data/hg38/CTCF/chr3toY_pos_shuf.bed)

To obtain the files for the other TFs used in the original study, simply replace "CTCF" with "CEBPA", "Hnf4a", or "RXRA" in the link.

Hope this helps!

Kelly
